name: Deploy backend to heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend && yarn install
      - run: cd backend && yarn build
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_branch: "main"
          email: ${{secrets.HEROKU_EMAIL}}
          subfolder: "backend"
